#!/bin/bash

set -xeo pipefail
chmod +x pic || curl https://raw.githubusercontent.com/qtvhao/picloud/main/pic -o pic && chmod +x pic

args=("$@")
IDENTITY_FILE=${args[0]}
if [ -z "$IDENTITY_FILE" ]; then
  echo "Please provide identity file"
  exit 1
fi
# Create on nodes
NODES=`cat NODES || ./pic list-nodename $IDENTITY_FILE | awk '{print $1}' | tr '\n' ' '`
echo $NODES | tee NODES

echo "Create on nodes: $NODES"
for node in $NODES; do
  echo "Create on node: $node"

  scp -o StrictHostKeyChecking=no -i $IDENTITY_FILE create $node:~/
  ssh -o StrictHostKeyChecking=no -i $IDENTITY_FILE $node "chmod +x create"
  ssh -t -o StrictHostKeyChecking=no -i $IDENTITY_FILE $node "./create || exit 1"
done
