#!/bin/bash

set -xeo pipefail
chmod +x pic || curl https://raw.githubusercontent.com/qtvhao/picloud/main/pic -o pic && chmod +x pic

args=("$@")
IDENTITY_FILE=${args[0]}
if [ -z "$IDENTITY_FILE" ]; then
  echo "Please provide identity file"
  exit 1
fi
# Create on nodes
NODES=`./pic list-nodename $IDENTITY_FILE | awk '{print $1}' | tr '\n' ' '`

echo "Create on nodes: $NODES"
for node in $NODES; do
  echo "Create on node: $node"
  ssh -o StrictHostKeyChecking=no -i $IDENTITY_FILE $node 'bash -s' < create
done
