#!/bin/bash

THIS_IP_ADDRESS=`hostname -I | awk '{print $1}'`
THIS_NODE=`kubectl get nodes -o json | jq -e '.items[] | select(.status.addresses[] | select(.type=="InternalIP" and .address=="'$THIS_IP_ADDRESS'")) | .metadata.name' | tr -d '"'`
echo "THIS_NODE: $THIS_NODE"
# We need to create a service of type NodePort to expose the redis service
# Use port 6379 on $THIS_NODE to access the redis service

kubectl apply -f - <<EOF
apiVersion: v1
kind: Service
metadata:
  name: redis-nodeport
  namespace: apis-development
spec:
    type: NodePort
    selector:
        app: redis
    ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
      nodePort: 31379
EOF
